### ISSUE TITLE
Erro ao Enviar NFe com XML e Acertificado A3

### ISSUE THREAD

**Issue by fabianofsantos** [Samuel-Oliveira/Java_NFe#124]
WebService - https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NFeAutorizacao4?wsdl
out 24, 2018 10:08:39 PM org.apache.axis2.transport.http.impl.httpclient3.HTTPSenderImpl sendViaPost
INFORMAÇÕES: Unable to sendViaPost to url[https://nfehomolog.sefaz.pe.gov.br/nfe-service/services/NFeAutorizacao4?wsdl]
java.net.UnknownHostException: nfehomolog.sefaz.pe.gov.br
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at br.com.samuelweb.certificado.SocketFactoryDinamico.createSocket(SocketFactoryDinamico.java:42)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.axis2.transport.http.impl.httpclient3.HTTPSenderImpl.executeMethod(HTTPSenderImpl.java:872)
	at org.apache.axis2.transport.http.impl.httpclient3.HTTPSenderImpl.sendViaPost(HTTPSenderImpl.java:212)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:121)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:403)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:234)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:431)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:399)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:150)
	at br.inf.portalfiscal.www.nfe_400.wsdl.NFeAutorizacao.NFeAutorizacao4Stub.nfeAutorizacaoLote(NFeAutorizacao4Stub.java:174)
	at br.com.samuelweb.nfe.Enviar.enviaNfe(Enviar.java:155)
	at br.com.samuelweb.nfe.Nfe.enviarNfe(Nfe.java:185)
	at com.mycompany.mavenproject1.NewMain.main(NewMain.java:40)

Erro:nfehomolog.sefaz.pe.gov.br

Recebo isso no console

**Comment by fabianofsantos** [comment]
Pode fechar a issue, consegui enviar a nota com Certificado A3. Parabéns pelo trabalho...
