### ISSUE TITLE
Problema ao Iniciar as Configurações

### ISSUE THREAD

**Issue by ivanildos** [Samuel-Oliveira/Java_NFe#162]
Bom dia!
 -Ao enviar a nota para sefaz está dando um erro de null ao iniciar as configurações o que poderia ser. Na saída impressa pela biblioteca está apresentando  "Cnpj/Cpf Certificado: null". Segue a exceção:

java.lang.NullPointerException at br.com.swconsultoria.nfe.util.ConfiguracoesUtil.iniciaConfiguracoes(ConfiguracoesUtil.java:64)
	at br.com.swconsultoria.nfe.Nfe.montaNfe(Nfe.java:127)

O resultado na saída do console:

 Alias Certificado: XXXXXXXXXXXXXXXXX
 Vencimento Certificado: 2020-03-20
 Cnpj/Cpf Certificado: null
 Ambiente: Homologação - Estado: XXXXXXXXXXXXX
#########################################################

**Comment by Samuel-Oliveira** [comment]
Tudo bom? Qual versão está utilizando?
Usa Maven ou External jar?

**Comment by ivanildos** [comment]
Estou utilizando a versão 4.00.11
Uso External jar

**Comment by Samuel-Oliveira** [comment]
Ivanildo bastante estranho, pelo erro ele não está conseguindo pegar o Documento do Certificado.
Qual modo de certificado está utilizando?
A1 Arquivo, A1 Pfx, Windows ou A3? 

Pode enviar o código de como está configurando e inicializando o certificado?

**Comment by Andre-Mazzardo** [comment]
estou tentando usar da seguinte forma: 
public ConfiguracoesNfe iniciaConfiguracoes() throws FileNotFoundException, CertificadoException  {

		String senha = usuarioLogado.getUsuario().getUnidade().getConfiguracaoFiscal().getSenhaCertificado();

		byte[] certificadoBytes = usuarioLogado.getUsuario().getUnidade().getConfiguracaoFiscal().getCertificado();
				
		Certificado certificado = CertificadoService.certificadoPfxBytes(certificadoBytes, senha);
				
		if(IDUtils.getAmbiente(usuarioLogado.getUsuario().getUnidade()).equals("2")) {

			return ConfiguracoesNfe.criarConfiguracoes(
					EstadosEnum.valueOf(usuarioLogado.getUsuario().getUnidade().getUf()), AmbienteEnum.HOMOLOGACAO,
					certificado, "C://schemas");
		} else {

			return ConfiguracoesNfe.criarConfiguracoes(
					EstadosEnum.valueOf(usuarioLogado.getUsuario().getUnidade().getUf()), AmbienteEnum.PRODUCAO,
					certificado, "C://schemas");
		}

	}

para mim o erro estora na seguinte linha : certificado.setCnpjCpf(getDocumentoFromCertificado(certificado, keyStore));

erro abaixo:
GRAVE: org.bouncycastle.asn1.ASN1InputStream.readObject()Lorg/bouncycastle/asn1/DERObject;
java.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1InputStream.readObject()Lorg/bouncycastle/asn1/DERObject;
	at br.com.swconsultoria.certificado.CertificadoService.lambda$null$9(CertificadoService.java:440)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at br.com.swconsultoria.certificado.CertificadoService.lambda$getDocumentoFromCertificado$10(CertificadoService.java:436)
	at java.util.Optional.ifPresent(Optional.java:159)
	at br.com.swconsultoria.certificado.CertificadoService.getDocumentoFromCertificado(CertificadoService.java:435)
	at br.com.swconsultoria.certificado.CertificadoService.setDadosCertificado(CertificadoService.java:79)
	at br.com.swconsultoria.certificado.CertificadoService.certificadoPfxBytes(CertificadoService.java:62)
	at com.amsoft.erp.util.CertificadoInit.iniciaConfiguracoes(CertificadoInit.java:30)

**Comment by Samuel-Oliveira** [comment]
@Andre-Mazzardo peço que não post em duvidas já ativas com problemas diferentes.
Isso bagunça e atrapalha. Crie um novo tópico por favor que eu te ajudo em seu problema.

**Comment by ivanildos** [comment]
@Samuel-Oliveira detectei que havia um arquivo no sistema com o mesmo nome de um dos arquivos da sua biblioteca e estava importando as informações desse arquivo ao invés do arquivo correto da biblioteca, troquei a importação e parou de ocorrer a exceção.

Agradeço pela atenção e peço desculpas por ter tomado seu tempo!
