### ISSUE TITLE
Connection reset ao consumir servicos de homologação da Uf MT

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_NFe#174]
Boa tarde @Samuel-Oliveira estou testando serviços em homologação com a api e vejo que ao consumir os serviços de homologação estou recebendo um Conect Reset da api porem testo o serviço de outra aplicação que não usa a api e a mesma diz que o serviço está em operação, consulto pelo site e também mostra em operação. Lembrando que isso ocorre somente para serviços em homologação.
`
br.com.swconsultoria.nfe.exception.NfeException: Connection reset
	at br.com.swconsultoria.nfe.Status.statusServico(Status.java:86)
	at br.com.swconsultoria.nfe.Nfe.statusServico(Nfe.java:60)
	at com.softjava.helpers.nfe.ConsultaStatusServicoNFe.consultarNFe(ConsultaStatusServicoNFe.java:26)
	at com.softjava.formulario.FormPrincipal.menuItemStatusNFeActionPerformed(FormPrincipal.java:2973)
	at com.softjava.formulario.FormPrincipal.access$10400(FormPrincipal.java:198)
	at com.softjava.formulario.FormPrincipal$105.actionPerformed(FormPrincipal.java:1715)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`
![uninfe](https://user-images.githubusercontent.com/3025776/62826024-d0848880-bb82-11e9-85bd-cc486e890f5f.png)

**Já testei em ambientes diferentes com maquinas e internet diferente**

**Comment by LeonardoWiest** [comment]
Prezados, estou com o mesmo problema. Aparentemente acredito que seja algo referente ao protocolo de comunicação (TLS 1.2) com a SEFAZ do MT. O erro ocorre no momento em que é feita a tentativa de abertura de conexão com WS, utilizando o Axis2. Para mim ocorre na emissão de NFC-e e em alguns casos na consulta de status.

**Comment by resplandes** [comment]
**Tive hoje um retorno da sefaz.**
![erro_conection_reset](https://user-images.githubusercontent.com/3025776/62868053-bd88ca00-bce2-11e9-8a7b-748fd230e3b0.jpg)

**Comment by LeonardoWiest** [comment]
Temos alguma solução para isso já? Para mim ainda está ocorrendo.

**Comment by Samuel-Oliveira** [comment]
Olá Senhroes @LeonardoWiest e @resplandes ;
Hoje fiz exaustivos testes: 
- Alterei os diversos de tipos de TLS : TLS, TLSv1, TLSv1.1 e TLSv1.2 (Padrão).
- Alterei para conexão Via Properties

E nada teve resultado.
Como se trata somente dos servidores de Homologação, ainda não é algo preocupante.
Qlq ideia nova de testes que tiverem me avisem... Estou a disposição para ajuda-los.

**Comment by Samuel-Oliveira** [comment]
Podem confirmar o Status pessoal @LeonardoWiest @resplandes?

**Comment by resplandes** [comment]
Boa tarde, ainda persiste o problema :(

**Comment by resplandes** [comment]
Bom dia, em contato com a Sefaz-MT fui informado que a unica diferença que está havendo entre o ambiente de produção e o de homologação é que o de homologação está demorando um pouco mais para reportar suas respostas, informado sobre o problema eles pediram para aumentar o tempo de aguardo da resposta que provavelmente normaliza

**Comment by Samuel-Oliveira** [comment]
Nada Meu patrão... Tem que ser feito este teste do aumento de resposta, mas to correndo d+ com outros projetos!

**Comment by resplandes** [comment]
Tem algo que posso fazer ? Mudar isso somente para eu mesmo testar pois ajudaria muito nos testes :(

**Comment by Samuel-Oliveira** [comment]
@resplandes Teste a nova versão que pode ser configurado mais retry! Talvez de bom!

**Comment by resplandes** [comment]
Bom dia, @Samuel-Oliveira  fiz o teste com a nova biblioteca e funcionou ai fui testar a antiga que ja tinha desistido do modo de homologação e agora ta funcionando também, sera que a sefaz tomou jeito ? vou testar mais e reporto aqui.

**Comment by resplandes** [comment]
@Samuel-Oliveira  resolvido com o retry que é a quantidade de tentativas :)
