### ISSUE TITLE
Erro no parse NFeAutorizacao4Stub.NfeResultMsg

### ISSUE THREAD

**Issue by andreiox** [Samuel-Oliveira/Java_NFe#188]
Quando tentando autorizar uma NFe, ocorre um erro ao tentar montar a classe de resultado NfeResultMsg.
A NFe é autorizada junto a sefaz mas uma NfeException é lançada.

Logs:

```
#########################################################
    Api Java Nfe - Versão 4.00.12        
 Samuel Olivera - samuel@swconsultoria.com.br 
            Tipo Certificado: ARQUIVO_BYTES
 Alias Certificado: {5E7339CA-2C01-4099-B8E3-55294BE2BD81}
 Vencimento Certificado: 2020-12-11
 Cnpj/Cpf Certificado: 08684547000165
 Ambiente: Homologação - Estado: Minas Gerais
#########################################################

2020-01-20 16:39:12.423  INFO 20601 --- [nio-8080-exec-1]                                          : [XML-ENVIO]: <?xml version="1.0" encoding="UTF-8"?><enviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><idLote>1</idLote><indSinc>1</indSinc><NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe versao="4.00" Id="NFe31200108684547000165550020000011231000111233"><ide><cUF>31</cUF><cNF>00011123</cNF><natOp>2</natOp><mod>55</mod><serie>2</serie><nNF>1123</nNF><dhEmi>2020-01-17T00:00:00-03:00</dhEmi><dhSaiEnt>2020-01-17T00:00:00-03:00</dhSaiEnt><tpNF>1</tpNF><idDest>1</idDest><cMunFG>3118601</cMunFG><tpImp>1</tpImp><tpEmis>1</tpEmis><cDV>3</cDV><tpAmb>2</tpAmb><finNFe>1</finNFe><indFinal>1</indFinal><indPres>2</indPres><procEmi>0</procEmi><verProc>1.0</verProc></ide><emit><CNPJ>08684547000165</CNPJ><xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome><xFant>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xFant><enderEmit><xLgr>PC LOUIS ENSCH</xLgr><nro>240</nro><xBairro>CIDADE INDUSTRIAL</xBairro><cMun>3118601</cMun><xMun>Contagem</xMun><UF>MG</UF><CEP>32210050</CEP><cPais>1058</cPais><fone>3199999999</fone></enderEmit><IE>0010660660016</IE><CRT>3</CRT></emit><dest><CNPJ>38761695000105</CNPJ><xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome><enderDest><xLgr>ISAAC AIZEMBERG</xLgr><nro>100</nro><xBairro>PARQUE DOS PÁSSAROS</xBairro><cMun>3548708</cMun><xMun>Sao Bernardo do Campo</xMun><UF>SP</UF><CEP>09861005</CEP><cPais>1058</cPais><fone>1211112233</fone></enderDest><indIEDest>9</indIEDest></dest><det nItem="1"><prod><cProd>P13</cProd><cEAN>SEM GTIN</cEAN><xProd>ONU1075 GAS LP, 2.1, 13 KG</xProd><NCM>27111910</NCM><CEST>0601101</CEST><CFOP>5656</CFOP><uCom>KG</uCom><qCom>1.0000</qCom><vUnCom>140.000000</vUnCom><vProd>140.00</vProd><cEANTrib>SEM GTIN</cEANTrib><uTrib>KG</uTrib><qTrib>1.0000</qTrib><vUnTrib>140.000000</vUnTrib><indTot>1</indTot><comb><cProdANP>210203001</cProdANP><descANP>GLP</descANP><pGLP>100.0000</pGLP><vPart>1</vPart><UFCons>MG</UFCons></comb></prod><imposto><ICMS><ICMSST><orig>0</orig><CST>60</CST><vBCSTRet>0.00</vBCSTRet><pST>0.00</pST><vICMSSubstituto>0.00</vICMSSubstituto><vICMSSTRet>0.00</vICMSSTRet><vBCSTDest>0.00</vBCSTDest><vICMSSTDest>0.00</vICMSSTDest></ICMSST></ICMS><IPI><cEnq>999</cEnq><IPINT><CST>53</CST></IPINT></IPI><PIS><PISNT><CST>04</CST></PISNT></PIS><COFINS><COFINSNT><CST>04</CST></COFINSNT></COFINS></imposto></det><total><ICMSTot><vBC>0.00</vBC><vICMS>0.00</vICMS><vICMSDeson>0.00</vICMSDeson><vFCP>0.00</vFCP><vBCST>0.00</vBCST><vST>0.00</vST><vFCPST>0.00</vFCPST><vFCPSTRet>0.00</vFCPSTRet><vProd>140.00</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vII>0.00</vII><vIPI>0.00</vIPI><vIPIDevol>0.00</vIPIDevol><vPIS>0.00</vPIS><vCOFINS>0.00</vCOFINS><vOutro>0.00</vOutro><vNF>140.00</vNF></ICMSTot><retTrib/></total><transp><modFrete>0</modFrete><transporta><CNPJ>92015816000107</CNPJ><xNome>CLIENTE 2208</xNome><IE>ISENTO</IE><xEnder>PARQUE DOS PÁSSAROS, ISAAC AIZEMBERG, 100, 09861-005</xEnder><xMun>SÃO BERNARDO DO CAMPO</xMun><UF>SP</UF></transporta><vol><qVol>0</qVol><esp>Caixa</esp><pesoL>13.000</pesoL><pesoB>0.000</pesoB></vol></transp><cobr><fat><nFat>24236</nFat><vOrig>140.00</vOrig><vDesc>0.00</vDesc><vLiq>140.00</vLiq></fat><dup><nDup>001</nDup><dVenc>2020-01-17</dVenc><vDup>140.00</vDup></dup></cobr><pag><detPag><indPag>1</indPag><tPag>99</tPag><vPag>140.00</vPag></detPag></pag><infAdic><infCpl>Baseado em Pedidos de venda 82653.</infCpl></infAdic></infNFe><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#NFe31200108684547000165550020000011231000111233"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>fv59cuQYDYGv5ZvQ6uYnu11+dy0=</DigestValue></Reference></SignedInfo><SignatureValue>CzuvhJH3NvjFm9syeN7p8FDwOvQul6xcNOayg3g7XmdqrmsKzI1udiPvnlLPse2VukiQ4I8wD5wblnm/iLHJparl1O21uBS1yuvgd8AgFSKbM1oob3U3XY9DaIs72k2roMfR91GMx5nIGLJRo0lpe0ZkBpxVqr0EfvhKIWsiVjIvdV6hWtxuWG142JuNTPu4jPgQo62t2U//SHHIW1DzZ55/hEks0kL/xeF+/eukIcps4tTQ53IWYlE2qB0oE1R//LDV63JM2mhGIXyqlFjX1ltI96sCQGkGImJpqWhphsTq6wEzSrLeAddblasxwknmkymU0SmhQUTXxUXK68Vp3g==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIHjzCCBXegAwIBAgIUSnGczPm7ihXOEq+CSmF8iVciBzQwDQYJKoZIhvcNAQELBQAwejELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEeMBwGA1UEAxMVQUMgRElHSVRBTFNJR04gUkZCIEcyMB4XDTE5MTIxMTIwMjMyMloXDTIwMTIxMTIwMjMyMlowgd4xCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMQswCQYDVQQIEwJNRzERMA8GA1UEBxMIQ29udGFnZW0xNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEWMBQGA1UECxMNUkZCIGUtQ05QSiBBMTEXMBUGA1UECxMOMjUzMzI2NjIwMDAxOTAxMTAvBgNVBAMTKE1BR05FU0lUQSBSRUZSQVRBUklPUyBTIEE6MDg2ODQ1NDcwMDAxNjUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCmYOa4dRPGKRjFkx1csie10+urmkZn4PPpy65GGJnYk8HH84PsagjYphqTA3P+0pIIMkauA1r7Vybos+3dKt3ucYDdZRCjsmB0QdP3BlLh4kDvNl6rHfRswLfKp5uwsifChwvJpW8SjdbpTZhrPuRnrIzcIxmB5pYtqOw6hABfR+QYPlDXLZn9UROY3N44xW2UN+VlcKeuzwRCzBLvuRHjuoeeY7pXT604u0m64KLM5Zimjm+CDuhn4ZbgmGiegDzMfv1XQM8ZlIPBuvd4CQEfcpy53rarMJC/EsH9mxeSDiIkBtkfvcyPOsaLcLA8cTzEUgC8b+ChzvDTXVPQrVJAgMBAAGjggKmMIICojAOBgNVHQ8BAf8EBAMCBeAwbQYIKwYBBQUHAQEEYTBfMF0GCCsGAQUFBzAChlFodHRwOi8vd3d3LmRpZ2l0YWxzaWduY2VydGlmaWNhZG9yYS5jb20uYnIvcmVwb3NpdG9yaW8vcmZiL0FDRElHSVRBTFNJR05SRkJHMi5wN2IwHwYDVR0jBBgwFoAUyk9DCfZI4ErVb+UtXYdrqSmOR3swXQYDVR0gBFYwVDBSBgZgTAECASwwSDBGBggrBgEFBQcCARY6aHR0cDovL3d3dy5kaWdpdGFsc2lnbmNlcnRpZmljYWRvcmEuY29tLmJyL3JlcG9zaXRvcmlvL3JmYjAJBgNVHRMEAjAAMIGxBgNVHR8EgakwgaYwV6BVoFOGUWh0dHA6Ly93d3cuZGlnaXRhbHNpZ25jZXJ0aWZpY2Fkb3JhLmNvbS5ici9yZXBvc2l0b3Jpby9yZmIvQUNESUdJVEFMU0lHTlJGQkcyLmNybDBLoEmgR4ZFaHR0cDovL3d3dy5kaWdpdGFsdHJ1c3QuY29tLmJyL3JlcG9zaXRvcmlvL3JmYi9BQ0RJR0lUQUxTSUdOUkZCRzIuY3JsMIHCBgNVHREEgbowgbeBHlJvbXVsby5MaXNib2FAcmhpbWFnbmVzaXRhLmNvbaA4BgVgTAEDBKAvBC0xMzExMTk4MzA1NTM2OTA1NjYwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDCgJwYFYEwBAwKgHgQcVEhJQUdPIE1FTkRFUyBEQSBNT1RUQSBDT1VUT6AZBgVgTAEDA6AQBA4wODY4NDU0NzAwMDE2NaAXBgVgTAEDB6AOBAwwMDAwMDAwMDAwMDAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMA0GCSqGSIb3DQEBCwUAA4ICAQBSaBgcObiXKLgZbcwX0NJ2z/pcEcCLmH/7uCJ4aS823YGDu/oVCEDL5E2LIZz+yHRZL61P7iSxD4A3ncUwMyr2l9CU3ay3F9wG7a/AltUylH8yCZsHVOPTYRD2PytgCfGXwh9IIH3Pg+rS+l/h0frS0sfPczBG4OWH8bcqTEICW8blJsY/3AdIQp+5gugGPflriunVXa04YbT0c01IvqscNqveys9REICluvqD2cRYZohsBdisUjzxgsfx2u+Lh9Vprrca/YINIuN5yObcC6/4K9AYM2W1qATftb6ZtOmlK1OcYKSdYNEIxwsuMdflOZZA9e3QM768C8fYXfDAIVO8A/3PLZKa2BfFK6BEHe+/WnHOctCP95UnaG2V9dEk/c3KDOLyiGuF2km4zJHqRGEXoqPNIHqjtR0ZgCdROaCBEmRC/K2R6Cjia6XlBk1R1CsP+og+hBEp/9zTzrx0pWvHsp7wQHvOhM+El0ZM8K9Psan1AHMoM+iN6WnMTynPWRkwy7DWp2HKyEjElSkAcMkkbj8jFhxL69HxCU8m1NfebkiJRi1v3L0PY9DipPkG63QDZbpkUHIcAz9MjJHKcj/u7gE03gNyzVVaEPl9rJxPWV6TZbBfERw0deFHuCH4elYceYaMKw5EtNl+8cXXHlFqm5I6KvZAJ8dNjPf3oV+0+Q==</X509Certificate></X509Data></KeyInfo></Signature></NFe></enviNFe>
2020-01-20 16:39:20.257  INFO 20601 --- [nio-8080-exec-1]                                          : [URL]: ENVIO: https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeAutorizacao4
br.com.swconsultoria.nfe.exception.NfeException: br.inf.portalfiscal.jms.ProdutorTxtMQ.<init>(Ljava/lang/String;Ljava/io/Serializable;Ljava/lang/String;Ljava/lang/String;)V
	at br.com.swconsultoria.nfe.Enviar.enviaNfe(Enviar.java:131)
	at br.com.swconsultoria.nfe.Nfe.enviarNfe(Nfe.java:142)
```

Na segunda tentativa de envio (para mostrar que a NFe está autorizada):

```
#########################################################
    Api Java Nfe - Versão 4.00.12        
 Samuel Olivera - samuel@swconsultoria.com.br 
            Tipo Certificado: ARQUIVO_BYTES
 Alias Certificado: {5E7339CA-2C01-4099-B8E3-55294BE2BD81}
 Vencimento Certificado: 2020-12-11
 Cnpj/Cpf Certificado: 08684547000165
 Ambiente: Homologação - Estado: Minas Gerais
#########################################################

2020-01-20 16:45:36.157  INFO 20601 --- [nio-8080-exec-2]                                          : [XML-ENVIO]: <?xml version="1.0" encoding="UTF-8"?><enviNFe versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><idLote>1</idLote><indSinc>1</indSinc><NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe versao="4.00" Id="NFe31200108684547000165550020000011231000111233"><ide><cUF>31</cUF><cNF>00011123</cNF><natOp>2</natOp><mod>55</mod><serie>2</serie><nNF>1123</nNF><dhEmi>2020-01-17T00:00:00-03:00</dhEmi><dhSaiEnt>2020-01-17T00:00:00-03:00</dhSaiEnt><tpNF>1</tpNF><idDest>1</idDest><cMunFG>3118601</cMunFG><tpImp>1</tpImp><tpEmis>1</tpEmis><cDV>3</cDV><tpAmb>2</tpAmb><finNFe>1</finNFe><indFinal>1</indFinal><indPres>2</indPres><procEmi>0</procEmi><verProc>1.0</verProc></ide><emit><CNPJ>08684547000165</CNPJ><xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome><xFant>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xFant><enderEmit><xLgr>PC LOUIS ENSCH</xLgr><nro>240</nro><xBairro>CIDADE INDUSTRIAL</xBairro><cMun>3118601</cMun><xMun>Contagem</xMun><UF>MG</UF><CEP>32210050</CEP><cPais>1058</cPais><fone>3199999999</fone></enderEmit><IE>0010660660016</IE><CRT>3</CRT></emit><dest><CNPJ>38761695000105</CNPJ><xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome><enderDest><xLgr>ISAAC AIZEMBERG</xLgr><nro>100</nro><xBairro>PARQUE DOS PÁSSAROS</xBairro><cMun>3548708</cMun><xMun>Sao Bernardo do Campo</xMun><UF>SP</UF><CEP>09861005</CEP><cPais>1058</cPais><fone>1211112233</fone></enderDest><indIEDest>9</indIEDest></dest><det nItem="1"><prod><cProd>P13</cProd><cEAN>SEM GTIN</cEAN><xProd>ONU1075 GAS LP, 2.1, 13 KG</xProd><NCM>27111910</NCM><CEST>0601101</CEST><CFOP>5656</CFOP><uCom>KG</uCom><qCom>1.0000</qCom><vUnCom>140.000000</vUnCom><vProd>140.00</vProd><cEANTrib>SEM GTIN</cEANTrib><uTrib>KG</uTrib><qTrib>1.0000</qTrib><vUnTrib>140.000000</vUnTrib><indTot>1</indTot><comb><cProdANP>210203001</cProdANP><descANP>GLP</descANP><pGLP>100.0000</pGLP><vPart>1</vPart><UFCons>MG</UFCons></comb></prod><imposto><ICMS><ICMSST><orig>0</orig><CST>60</CST><vBCSTRet>0.00</vBCSTRet><pST>0.00</pST><vICMSSubstituto>0.00</vICMSSubstituto><vICMSSTRet>0.00</vICMSSTRet><vBCSTDest>0.00</vBCSTDest><vICMSSTDest>0.00</vICMSSTDest></ICMSST></ICMS><IPI><cEnq>999</cEnq><IPINT><CST>53</CST></IPINT></IPI><PIS><PISNT><CST>04</CST></PISNT></PIS><COFINS><COFINSNT><CST>04</CST></COFINSNT></COFINS></imposto></det><total><ICMSTot><vBC>0.00</vBC><vICMS>0.00</vICMS><vICMSDeson>0.00</vICMSDeson><vFCP>0.00</vFCP><vBCST>0.00</vBCST><vST>0.00</vST><vFCPST>0.00</vFCPST><vFCPSTRet>0.00</vFCPSTRet><vProd>140.00</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vII>0.00</vII><vIPI>0.00</vIPI><vIPIDevol>0.00</vIPIDevol><vPIS>0.00</vPIS><vCOFINS>0.00</vCOFINS><vOutro>0.00</vOutro><vNF>140.00</vNF></ICMSTot><retTrib/></total><transp><modFrete>0</modFrete><transporta><CNPJ>92015816000107</CNPJ><xNome>CLIENTE 2208</xNome><IE>ISENTO</IE><xEnder>PARQUE DOS PÁSSAROS, ISAAC AIZEMBERG, 100, 09861-005</xEnder><xMun>SÃO BERNARDO DO CAMPO</xMun><UF>SP</UF></transporta><vol><qVol>0</qVol><esp>Caixa</esp><pesoL>13.000</pesoL><pesoB>0.000</pesoB></vol></transp><cobr><fat><nFat>24236</nFat><vOrig>140.00</vOrig><vDesc>0.00</vDesc><vLiq>140.00</vLiq></fat><dup><nDup>001</nDup><dVenc>2020-01-17</dVenc><vDup>140.00</vDup></dup></cobr><pag><detPag><indPag>1</indPag><tPag>99</tPag><vPag>140.00</vPag></detPag></pag><infAdic><infCpl>Baseado em Pedidos de venda 82653.</infCpl></infAdic></infNFe><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#NFe31200108684547000165550020000011231000111233"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>fv59cuQYDYGv5ZvQ6uYnu11+dy0=</DigestValue></Reference></SignedInfo><SignatureValue>CzuvhJH3NvjFm9syeN7p8FDwOvQul6xcNOayg3g7XmdqrmsKzI1udiPvnlLPse2VukiQ4I8wD5wblnm/iLHJparl1O21uBS1yuvgd8AgFSKbM1oob3U3XY9DaIs72k2roMfR91GMx5nIGLJRo0lpe0ZkBpxVqr0EfvhKIWsiVjIvdV6hWtxuWG142JuNTPu4jPgQo62t2U//SHHIW1DzZ55/hEks0kL/xeF+/eukIcps4tTQ53IWYlE2qB0oE1R//LDV63JM2mhGIXyqlFjX1ltI96sCQGkGImJpqWhphsTq6wEzSrLeAddblasxwknmkymU0SmhQUTXxUXK68Vp3g==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIHjzCCBXegAwIBAgIUSnGczPm7ihXOEq+CSmF8iVciBzQwDQYJKoZIhvcNAQELBQAwejELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEeMBwGA1UEAxMVQUMgRElHSVRBTFNJR04gUkZCIEcyMB4XDTE5MTIxMTIwMjMyMloXDTIwMTIxMTIwMjMyMlowgd4xCzAJBgNVBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMQswCQYDVQQIEwJNRzERMA8GA1UEBxMIQ29udGFnZW0xNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEWMBQGA1UECxMNUkZCIGUtQ05QSiBBMTEXMBUGA1UECxMOMjUzMzI2NjIwMDAxOTAxMTAvBgNVBAMTKE1BR05FU0lUQSBSRUZSQVRBUklPUyBTIEE6MDg2ODQ1NDcwMDAxNjUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCmYOa4dRPGKRjFkx1csie10+urmkZn4PPpy65GGJnYk8HH84PsagjYphqTA3P+0pIIMkauA1r7Vybos+3dKt3ucYDdZRCjsmB0QdP3BlLh4kDvNl6rHfRswLfKp5uwsifChwvJpW8SjdbpTZhrPuRnrIzcIxmB5pYtqOw6hABfR+QYPlDXLZn9UROY3N44xW2UN+VlcKeuzwRCzBLvuRHjuoeeY7pXT604u0m64KLM5Zimjm+CDuhn4ZbgmGiegDzMfv1XQM8ZlIPBuvd4CQEfcpy53rarMJC/EsH9mxeSDiIkBtkfvcyPOsaLcLA8cTzEUgC8b+ChzvDTXVPQrVJAgMBAAGjggKmMIICojAOBgNVHQ8BAf8EBAMCBeAwbQYIKwYBBQUHAQEEYTBfMF0GCCsGAQUFBzAChlFodHRwOi8vd3d3LmRpZ2l0YWxzaWduY2VydGlmaWNhZG9yYS5jb20uYnIvcmVwb3NpdG9yaW8vcmZiL0FDRElHSVRBTFNJR05SRkJHMi5wN2IwHwYDVR0jBBgwFoAUyk9DCfZI4ErVb+UtXYdrqSmOR3swXQYDVR0gBFYwVDBSBgZgTAECASwwSDBGBggrBgEFBQcCARY6aHR0cDovL3d3dy5kaWdpdGFsc2lnbmNlcnRpZmljYWRvcmEuY29tLmJyL3JlcG9zaXRvcmlvL3JmYjAJBgNVHRMEAjAAMIGxBgNVHR8EgakwgaYwV6BVoFOGUWh0dHA6Ly93d3cuZGlnaXRhbHNpZ25jZXJ0aWZpY2Fkb3JhLmNvbS5ici9yZXBvc2l0b3Jpby9yZmIvQUNESUdJVEFMU0lHTlJGQkcyLmNybDBLoEmgR4ZFaHR0cDovL3d3dy5kaWdpdGFsdHJ1c3QuY29tLmJyL3JlcG9zaXRvcmlvL3JmYi9BQ0RJR0lUQUxTSUdOUkZCRzIuY3JsMIHCBgNVHREEgbowgbeBHlJvbXVsby5MaXNib2FAcmhpbWFnbmVzaXRhLmNvbaA4BgVgTAEDBKAvBC0xMzExMTk4MzA1NTM2OTA1NjYwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDCgJwYFYEwBAwKgHgQcVEhJQUdPIE1FTkRFUyBEQSBNT1RUQSBDT1VUT6AZBgVgTAEDA6AQBA4wODY4NDU0NzAwMDE2NaAXBgVgTAEDB6AOBAwwMDAwMDAwMDAwMDAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMA0GCSqGSIb3DQEBCwUAA4ICAQBSaBgcObiXKLgZbcwX0NJ2z/pcEcCLmH/7uCJ4aS823YGDu/oVCEDL5E2LIZz+yHRZL61P7iSxD4A3ncUwMyr2l9CU3ay3F9wG7a/AltUylH8yCZsHVOPTYRD2PytgCfGXwh9IIH3Pg+rS+l/h0frS0sfPczBG4OWH8bcqTEICW8blJsY/3AdIQp+5gugGPflriunVXa04YbT0c01IvqscNqveys9REICluvqD2cRYZohsBdisUjzxgsfx2u+Lh9Vprrca/YINIuN5yObcC6/4K9AYM2W1qATftb6ZtOmlK1OcYKSdYNEIxwsuMdflOZZA9e3QM768C8fYXfDAIVO8A/3PLZKa2BfFK6BEHe+/WnHOctCP95UnaG2V9dEk/c3KDOLyiGuF2km4zJHqRGEXoqPNIHqjtR0ZgCdROaCBEmRC/K2R6Cjia6XlBk1R1CsP+og+hBEp/9zTzrx0pWvHsp7wQHvOhM+El0ZM8K9Psan1AHMoM+iN6WnMTynPWRkwy7DWp2HKyEjElSkAcMkkbj8jFhxL69HxCU8m1NfebkiJRi1v3L0PY9DipPkG63QDZbpkUHIcAz9MjJHKcj/u7gE03gNyzVVaEPl9rJxPWV6TZbBfERw0deFHuCH4elYceYaMKw5EtNl+8cXXHlFqm5I6KvZAJ8dNjPf3oV+0+Q==</X509Certificate></X509Data></KeyInfo></Signature></NFe></enviNFe>
2020-01-20 16:45:36.166  INFO 20601 --- [nio-8080-exec-2]                                          : [URL]: ENVIO: https://hnfe.fazenda.mg.gov.br/nfe2/services/NFeAutorizacao4
2020-01-20 16:45:37.957  INFO 20601 --- [nio-8080-exec-2]                                          : [XML-RETORNO]: <retEnviNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">
  <tpAmb>2</tpAmb>
  <verAplic>14.4.8-OR3</verAplic>
  <cStat>104</cStat>
  <xMotivo>Lote processado</xMotivo>
  <cUF>31</cUF>
  <dhRecbto>2020-01-20T15:45:37-03:00</dhRecbto>
  <protNFe versao="4.00">
    <infProt>
      <tpAmb>2</tpAmb>
      <verAplic>14.4.8-OR3</verAplic>
      <chNFe>31200108684547000165550020000011231000111233</chNFe>
      <dhRecbto>2020-01-20T15:45:36-03:00</dhRecbto>
      <digVal>fv59cuQYDYGv5ZvQ6uYnu11+dy0=</digVal>
      <cStat>204</cStat>
      <xMotivo>Rejeicao: Duplicidade de NF-e [nRec:310000069179169]</xMotivo>
    </infProt>
  </protNFe>
</retEnviNFe>
br.com.swconsultoria.nfe.exception.NfeException: 204 - Rejeicao: Duplicidade de NF-e [nRec:310000069179169]
	at br.com.swconsultoria.nfe.util.RetornoUtil.validaSincrono(RetornoUtil.java:207)
```

**Comment by Samuel-Oliveira** [comment]
Tudo bom?
br.inf.portalfiscal.jms.ProdutorTxtMQ, Não conheço este package... Você fez alguma alteração na biblioteca?

**Comment by andreiox** [comment]
Tudo bom e com você?
Não fiz, até baixei novamente do gradle a v4.00.12.

**Comment by Samuel-Oliveira** [comment]
Certo. Entre em Debug e veja o que vem dentro de result, na linha acima ao que ocorreu o erro!

**Comment by andreiox** [comment]
O erro está acontecendo dentro do método nfeAutorizacaoLote da classe NFeAutorizacao4Stub.
Está acontecendo na linha 176 `_operationClient.execute(true);`

**Comment by Samuel-Oliveira** [comment]
Muito Estranho. Possui certficado de outro estado? Caso não faça o teste em produção. PAra descartar o erro do servidor.

**Comment by andreiox** [comment]
Consegui emitir a mesma NFe (mudando alguns campos, claro) em SP. Provavelmente esse erro deve ser exclusivo do ambiente de homologação de MG.

**Comment by andreiox** [comment]
Tenho uma implementação em NodeJS da inutilização e em MG também está dando o mesmo erro.

XML de retorno:
```
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <soap:Body>
      <soap:Fault>
         <soap:Code>
            <soap:Value>soap:Receiver</soap:Value>
         </soap:Code>
         <soap:Reason>
            <soap:Text xml:lang="en">br.inf.portalfiscal.jms.ProdutorTxtMQ.&lt;init&gt;(Ljava/lang/String;Ljava/io/Serializable;Ljava/lang/String;Ljava/lang/String;)V</soap:Text>
         </soap:Reason>
      </soap:Fault>
   </soap:Body>
</soap:Envelope>
```

Agora é só esperar a correção por parte deles.
Muito obrigado.

**Comment by Samuel-Oliveira** [comment]
@andreiox Hj outras pessoas de MG reclamaram então infelizmente eh um erro deles.
