### ISSUE TITLE
Sefaz MT - NFCe /NFE em homologação com problemas de unknown

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_NFe#272]
Olá, a sefaz mt ficou fora por uns dias e ao retornar a lib em homologação apresenta esse erro, seja em consulta de status ou emissão, creio que todos eventos em homologação, conseguimos validar se é algo novo que está quebrando a lib ?

**SEFAZ_MT NFCe/NFe com **problemas** em homologação.**

> dez 23, 2023 7:07:17 AM br.com.swconsultoria.nfe.Status statusServico
> INFORMAÃ‡Ã•ES: [XML-ENVIO]: <?xml version="1.0" encoding="UTF-8"?><consStatServ versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>2</tpAmb><cUF>51</cUF><xServ>STATUS</xServ></consStatServ>
> dez 23, 2023 7:07:17 AM br.com.swconsultoria.nfe.util.WebServiceUtil getUrl
> INFORMAÃ‡Ã•ES: [URL]: STATUS_SERVICO: https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeStatusServico4?wsdl
> 2023-12-23 07:07:17,410 [SwingWorker-pool-1-thread-9] ERROR com.softjava.util.erro.ErroERPUtil - br.com.swconsultoria.nfe.exception.NfeException: unknown
> 	at br.com.swconsultoria.nfe.Status.statusServico(Status.java:103)
> 	at br.com.swconsultoria.nfe.Nfe.statusServico(Nfe.java:57)
> 	at com.softjava.modelo.nfe.v2.servico.sefaz.NFeStatusSefaz$1.doInBackground(NFeStatusSefaz.java:34)
> 	at com.softjava.modelo.nfe.v2.servico.sefaz.NFeStatusSefaz$1.doInBackground(NFeStatusSefaz.java:25)
> 	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at javax.swing.SwingWorker.run(SwingWorker.java:334)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: org.apache.axis2.AxisFault: unknown
> 	at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:508)
> 	at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:368)
> 	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:414)
> 	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
> 	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:150)
> 	at br.com.swconsultoria.nfe.wsdl.NFeStatusServico4.NFeStatusServico4Stub.nfeStatusServicoNF(NFeStatusServico4Stub.java:167)
> 	at br.com.swconsultoria.nfe.Status.statusServico(Status.java:96)
> 	... 9 more
> 
>

**Comment by resplandes** [comment]
Normalizou @Samuel-Oliveira mas pode testar !
