### ISSUE TITLE
Erro Null quando chama o metodo para listar os certificados do repositorio do windows

### ISSUE THREAD

**Issue by resplandes** [Samuel-Oliveira/Java_NFe#278]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.lang.String.<init>(String.java:566)
	at br.com.swconsultoria.certificado.CertificadoService.setDadosCertificado(CertificadoService.java:96)
	at br.com.swconsultoria.certificado.CertificadoService.listaCertificadosRepositorio(CertificadoService.java:167)
	at br.com.swconsultoria.certificado.CertificadoService.listaCertificadosWindows(CertificadoService.java:146)

**Comment by Samuel-Oliveira** [comment]
Resolvido versao 3.00.31
