### ISSUE TITLE
Erro ao carregar certificado

### ISSUE THREAD

**Issue by john182** [Samuel-Oliveira/Java_NFe#79]
boa noite, rodando a aplicação no container do wildfly ao tenta ler o certificado o mesmo :

Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_171]
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:98) [weld-core-impl-2.2.6.Final.jar:2014-10-03 10:05]
	... 141 more
Caused by: java.lang.NoClassDefFoundError: sun/security/pkcs11/wrapper/PKCS11Exception
	at com.chronos.util.CertificadoUtil.certificadoPfx(CertificadoUtil.java:65) [chronosnfe-4.0.0.jar:]
	at com.chronos.controll.IndexControll.initCertificado(IndexControll.java:200) [classes:]
	at com.chronos.controll.IndexControll.initd(IndexControll.java:96) [classes:]
	... 146 more
Caused by: java.lang.ClassNotFoundException: sun.security.pkcs11.wrapper.PKCS11Exception from [Module "deployment.technoserver-3.1.34.war:main" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.3.Final]
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.3.Final]
	... 149 more

**Comment by john182** [comment]
Sim eu estou usando o Maven, esse jar é o gerado pelo spring boot

**Comment by Samuel-Oliveira** [comment]
A Biblioteca bcprov-jdk16 estava causando o problema;
Solução foi ignorar ela no POM.

**Comment by henriquelssantiago** [comment]
Estou tendo o mesmo problema `"sun.security.pkcs11.wrapper.PKCS11Exception...."`

Estou utilizando o Wildfly 13.
Como ignorar essa dependência, percebi aqui que ela vem com a seguinte dependência: java-nfe
Fiz da seguinte maneira:

```
<dependency>
    <groupId>br.com.samuelweb</groupId>
    <artifactId>java-nfe</artifactId>
    <version>${java-nfe.version}</version>
    <exclusions>
        <exclusion>
            <artifactId>org.bouncycastle</artifactId>
            <groupId>bcprov-jdk16</groupId>
        </exclusion>
    </exclusions>
</dependency>
```

```
Caused by: java.lang.NoClassDefFoundError: sun/security/pkcs11/wrapper/PKCS11Exception
	at br.com.rcosta.omniaxml.schedule.Worker.work(Worker.java:31)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doMethodInterception(Jsr299BindingsInterceptor.java:90)
	at org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:101)
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.invocationmetrics.ExecutionTimeInterceptor.processInvocation(ExecutionTimeInterceptor.java:43)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:40)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:52)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.component.singleton.SingletonComponentInstanceAssociationInterceptor.processInvocation(SingletonComponentInstanceAssociationInterceptor.java:53)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:185)
	... 104 more
Caused by: java.lang.ClassNotFoundException: sun.security.pkcs11.wrapper.PKCS11Exception from [Module "deployment.omnia-xml.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 127 more
```

**Comment by henriquelssantiago** [comment]
Mas não obtive êxito.

**Comment by henriquelssantiago** [comment]
Você sabe dizer o motivo por dar esse erro com o wildfly?

**Comment by henriquelssantiago** [comment]
Opa Samuel!
Consegui identificar o erro, não sei se aqui será o melhor lugar pra colocar a solução, mas ai vai.

O problema eu tive com o Wildfly, não sei como se comporta com outro Servidor de aplicação ou Servlet container.

Essa lib requerida(`Caused by: java.lang.NoClassDefFoundError: sun/security/pkcs11/wrapper/PKCS11Exception`) vem com a própria JRE, por isso que é possível carregar o certificado normalmente em uma mainClass.
Mas por padrão, o Wildfly acaba não carregando todas as libs que vem com a JRE.
Então, faz-se necessário forçar o carregamento da lib, caso você precise utilizá-la:

Cria-se um arquivo `src/main/webapp/WEB-INF/jboss-deployment-structure.xml` com a seguinte estrutura:

```
<?xml version="1.0" encoding="UTF-8"?>
<jboss-deployment-structure xmlns="urn:jboss:deployment-structure:1.1">
    <deployment>
        <dependencies>
            <system export="true">
                <paths>
                    <path name="sun/security/x509"/>
                    <path name="sun/security/pkcs11"/>
                    <path name="sun/security/pkcs11/wrapper"/>
                </paths>
            </system>
        </dependencies>
    </deployment>
</jboss-deployment-structure>
```

**Problema resolvido!**

**Comment by renatoaguimaraes** [comment]
Olá!

Eu removi as dependências transitivas bcprov-jdk16.

```xml
<dependency>
    <groupId>br.com.samuelweb</groupId>
    <artifactId>java-nfe</artifactId>
    <version>${java-nfe.version}</version>
    <exclusions>
        <exclusion>
            <artifactId>org.bouncycastle</artifactId>
            <groupId>bcprov-jdk16</groupId>
        </exclusion>
    </exclusions>
</dependency>
```

 E adicionei bcprov-jdk16 versão 1.46.
       
```xml
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk16</artifactId>
    <version>1.46</version>
</dependency>
```

**Comment by quiksa** [comment]
Boa tarde!

Estou com o mesmo problema, adicionei o arquivo **jboss-deployment-structure.xml** na pasta conf. o exemplo acima, porem continua ocorrendo erro **sun/security/pkcs11/wrapper/PKCS11Exception**. Estou utilizando **Wildfly 18.0.1** e **jdk1.8.0_212**. Alguém sabe algum outro motivo que possa estar gerando este erro?

**Comment by quiksa** [comment]
> Boa tarde!
> 
> Estou com o mesmo problema, adicionei o arquivo **jboss-deployment-structure.xml** na pasta conf. o exemplo acima, porem continua ocorrendo erro **sun/security/pkcs11/wrapper/PKCS11Exception**. Estou utilizando **Wildfly 18.0.1** e **jdk1.8.0_212**. Alguém sabe algum outro motivo que possa estar gerando este erro?

Consegui resolver, foi algum problema na hora de executar o deploy pelo eclipse. Fiz o deploy manual e funcionou. Obrigado

**Comment by alinelsilva** [comment]
Olá boa tarde, estou implementando webService de Rio de Janeiro ao iniciar o teste em relação ao certificado, estou recebendo esse erro:

```
11:24:03,494 ERROR [org.springframework.boot.web.servlet.support.ErrorPageFilter] (default task-1) Forwarding to error page from request [/api/v1/ws/brazil/riodejaneiro/synchronizeRootByDate] due to exception [sun/security/pkcs11/wrapper/PKCS11Exception]: java.lang.NoClassDefFoundError: sun/security/pkcs11/wrapper/PKCS11Exception
	at deployment.ObsekiumWSCity.war//br.com.swconsultoria.nfse.rio.ConfiguracoesNFSe.<init>(ConfiguracoesNFSe.java:27)
```

Estou usando java 11 e Wildfly na versão 20 
Adicionei o arquivo jboss-deployment-structure.xml na pasta, coloquei no pom org.bouncycastle como exclusion, mas continua dando o erro.

**Comment by alinelsilva** [comment]
Eu consegui  resolver com a seguinte solução. (através de uma dica do fórum do Samuel)
Era um conflito com Wildfly.

Dentro da pasta Wildfly coloquei mais duas variáveis. 
Caminho: **wildfly/modules/system/layers/base/sun/jdk/main/module.xml**

```
<path name="sun/security/pkcs11/wrapper"/>
<path name="sun/security/provider/certpath"/>
```

![image](https://user-images.githubusercontent.com/22075156/141534186-c5883c58-911e-49a5-8db0-25e8f7d8a6a2.png)
